import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import './global.css'
import SessionWrapper from '../lib/SessionWrapper'
import Navbar from './components/topBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = (props: PropsWithChildren) => {
  const { children } = props
  return (
    <SessionWrapper>
    <html lang="en">
      <body>
        <Navbar />
        {children}
        </body>
    </html>
    </SessionWrapper>
  )
}

export default RootLayout
